server:
  port: 9008
spring:
  datasource:
    url: jdbc:mysql://iafoot.synology.me:3306/activiti?useSSL=false
#    url: jdbc:mysql://iafoot.synology.me:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: activiti
    password: activiti
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 1
      roles: admin

#mybatis:
#  mapperLocations: classpath:mapper/*Mapper.xml
  activiti:
    check-process-definitions: false # activti是否自动部署
    db-identity-used: false #是否使用activti自带的用户体系
    database-schema-update: true #是否每次都更新数据库
    process-definition-location-prefix: classpath:/processes/
    history-level: full #full最高级别

#  security:
#    basic:
#      enabled: false

